### ISSUE TITLE
Indexing asset files are limited to the first 1000

### ISSUE THREAD

**Issue by sparkalow** [fortrabbit/craft-object-storage#13] opened 2021-01-30 18:28 UTC
I uploaded ~4000 files to fortrabbit object storage using a GUI client. 

I attempted to run `php craft index-assets/one volumeHandle` to create ~4000 asset records -  it stopped at 1000.

I attempted to run `php craft index-assets/one volumeHandle 1001` to start at the next record (poor mans pagination) and it started with the same list of files. Same results starting at image 3000. It seems only the first 1000 images are returned no matter what.

**Comment by ostark** [comment] 2021-02-02 11:19
Listing 1000 files per directory is actually a known quirk:
https://help.fortrabbit.com/object-storage#toc-number-of-files

We will have a look at the index-assets/one command and see if we can provide a different way for indexing.

**Comment by sparkalow** [comment] 2021-02-03 20:31
As a workaround I was able to upload ~4000 files via the control panel in craft. Drag and drop all 4k, then wait. This on a 2016 macbook pro.

**Comment by ostark** [comment] 2021-02-08 21:56
@sparkalow the issue is not directly related to this Craft plugin. Sorry, it's a limitation of our current S3 implementation. 
There is an internal ticket in the backlog to fix this.

I'm closing this case.

**Closed as completed by ostark** 2021-02-08 21:56 UTC
